### ISSUE TITLE
Write function to set up linear programing problem

### ISSUE THREAD

**Issue by titipata** [titipata/paper-reviewer-matcher#1]
decrypt problem formulation of linear programming written by @daniel-acuna [here](https://github.com/daniel-acuna/reviewer_assignment/blob/master/reviewer_assignment_website/paper_reviewer_matcher/problem_formulation.py)

**Comment by daniel-acuna** [comment]
The key to decrypt it is the paper http://repository.upenn.edu/cgi/viewcontent.cgi?article=1934&context=cis_reports by Camilo Taylor :)

Thanks!

**Comment by titipata** [comment]
@daniel-acuna I guess I got it, can you take a look if it's now working properly?
