### ISSUE TITLE
Would you mind sending your test example file?

### ISSUE THREAD

**Issue by Bearsuny** [titipata/paper-reviewer-matcher#2]
Hi, I noticed that you used the **CNN18_MindMatchData.xlsx** as test example in `cnn_mind_matching.py`. I have searched this file by google, while unfortunately nothing. I don't know whether it is private or not. So would you mind if you send this file to my email `0bearsuny0@gmail.com` ? Thank you.

**Comment by titipata** [comment]
Hello @Bearsuny, yeah, unfortunately, the dataset belongs to the conference and might not be shared except you ask the organizer first. Let me know how it goes tho!

**Comment by Bearsuny** [comment]
Thank you for you reply. Unfortunately, I couldn't contact to the organizer. Maybe I can build a fake example according your code. Thank you again.
